name: GH Release

on:
  workflow_dispatch:
    inputs:
      fw:
        description: 'Create firmware release'
        required: false
        type: boolean
      fwu:
        description: 'Create firmware update release'
        required: false
        type: boolean
      mod:
        description: 'Create module release'
        required: false
        type: boolean
      modu:
        description: 'Create module update release'
        required: false
        type: boolean
      toolchain:
        description: 'Create toolchain release'
        required: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Create fw Release
      if: ${{ fromJSON(github.event.inputs.fw) }}
      uses: softprops/action-gh-release@master
      with:
        tag_name: firmware
        draft: false
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create fwu Release
      if: ${{ fromJSON(github.event.inputs.fwu) }}
      uses: softprops/action-gh-release@master
      with:
        tag_name: firmware_update
        draft: false
        make_latest: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create mod Release
      if: ${{ fromJSON(github.event.inputs.mod) }}
      uses: softprops/action-gh-release@master
      with:
        tag_name: module
        draft: false
        make_latest: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create modu Release
      if: ${{ fromJSON(github.event.inputs.modu) }}
      uses: softprops/action-gh-release@master
      with:
        tag_name: module_update
        draft: false
        make_latest: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create toolchain Release
      if: ${{ fromJSON(github.event.inputs.toolchain) }}
      uses: softprops/action-gh-release@master
      with:
        tag_name: toolchain
        draft: false
        make_latest: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
